spring:
  application:
    name: parlay-service

api-football:
  base-url: https://v3.football.api-sports.io
  api-key: ${API_FOOTBALL_KEY:your_api_key_here}
  league-id: 39 # Premier League
  season: 2025 # Current season
